// Nickname equivalence map (SPEC §9): first-name tokens in the same group
// are treated as the same name for fuzzy matching — search ranking now,
// dedupe scoring in Phase 9. Curated common English/European pairs.

const GROUPS: string[][] = [
  ["abigail", "abby", "gail"],
  ["albert", "al", "bert", "bertie"],
  ["alexander", "alex", "sasha", "xander", "sandy", "lex"],
  ["alexandra", "alex", "sandra", "sasha", "lexi"],
  ["alfred", "al", "alf", "fred", "freddie"],
  ["alison", "allison", "ali", "allie"],
  ["amanda", "mandy", "amy"],
  ["andrew", "andy", "drew"],
  ["angela", "angie"],
  ["anna", "ann", "anne", "annie", "ana"],
  ["anthony", "tony", "ant"],
  ["antonio", "tony", "toni"],
  ["arthur", "art", "artie"],
  ["barbara", "barb", "barbie", "babs"],
  ["benjamin", "ben", "benny", "benji"],
  ["bernard", "bernie", "bern"],
  ["beverly", "bev"],
  ["bradley", "brad"],
  ["brandon", "bran"],
  ["brian", "bryan"],
  ["bridget", "bridie"],
  ["caitlin", "kaitlin", "katelyn", "kate"],
  ["calvin", "cal"],
  ["cameron", "cam"],
  ["candace", "candy"],
  ["carolina", "carol", "carrie", "lina"],
  ["caroline", "carol", "carrie", "carly"],
  ["carolyn", "carol", "carrie"],
  ["catherine", "cathy", "cat", "cate", "kate", "katie", "kitty"],
  ["cecilia", "cece", "celia"],
  ["charles", "charlie", "chuck", "chas", "chip"],
  ["charlotte", "charlie", "lottie"],
  ["christina", "chris", "christy", "tina", "chrissy"],
  ["christine", "chris", "christy", "chrissy"],
  ["christopher", "chris", "topher", "kit"],
  ["cynthia", "cindy", "cyn"],
  ["daniel", "dan", "danny"],
  ["danielle", "dani", "elle"],
  ["david", "dave", "davey"],
  ["deborah", "debbie", "deb", "debra"],
  ["dennis", "denny"],
  ["diana", "diane", "di"],
  ["dominic", "dom", "nick"],
  ["donald", "don", "donny"],
  ["dorothy", "dot", "dottie", "dora"],
  ["douglas", "doug"],
  ["edward", "ed", "eddie", "ted", "teddy", "ned"],
  ["eleanor", "ellie", "nell", "nora", "ella"],
  ["elizabeth", "liz", "lizzie", "beth", "betsy", "betty", "eliza", "libby", "elsie"],
  ["emily", "em", "emmy"],
  ["eric", "erik", "rick"],
  ["eugene", "gene"],
  ["evelyn", "evie", "eve"],
  ["florence", "flo", "flossie"],
  ["frances", "fran", "frannie", "francie"],
  ["francesca", "fran", "frankie", "chessa"],
  ["francis", "frank", "fran", "frankie"],
  ["franklin", "frank", "frankie"],
  ["frederick", "fred", "freddie", "fritz", "rick"],
  ["gabriel", "gabe"],
  ["gabriella", "gabby", "ella", "gabi"],
  ["gerald", "gerry", "jerry"],
  ["gregory", "greg"],
  ["gwendolyn", "gwen"],
  ["harold", "harry", "hal"],
  ["henry", "hank", "harry", "hal"],
  ["isabella", "izzy", "bella", "belle", "isabel", "isabelle"],
  ["jacob", "jake", "jack"],
  ["jacqueline", "jackie", "jacqui"],
  ["james", "jim", "jimmy", "jamie", "jem"],
  ["janet", "jan"],
  ["jason", "jay"],
  ["jeffrey", "jeff", "geoffrey", "geoff"],
  ["jennifer", "jen", "jenny", "jenn"],
  ["jeremiah", "jerry", "jem"],
  ["jeremy", "jem", "jez"],
  ["jessica", "jess", "jessie"],
  ["joan", "joanie"],
  ["joanna", "jo", "joanne", "johanna"],
  ["john", "jack", "johnny", "jon"],
  ["jonathan", "jon", "jonny", "nathan"],
  ["joseph", "joe", "joey", "jos"],
  ["josephine", "jo", "josie"],
  ["joshua", "josh"],
  ["juan", "juanito"],
  ["judith", "judy", "jude"],
  ["julia", "julie", "jules"],
  ["julian", "jules"],
  ["justin", "jus"],
  ["katherine", "kate", "katie", "kathy", "kat", "kay", "katya", "kathryn"],
  ["kathleen", "kathy", "kate", "katie", "kath"],
  ["kenneth", "ken", "kenny"],
  ["kevin", "kev"],
  ["kimberly", "kim", "kimmy"],
  ["konstantin", "kostya", "konstantine"],
  ["lawrence", "larry", "laurence", "laurie"],
  ["leonard", "leo", "len", "lenny"],
  ["leopold", "leo"],
  ["lillian", "lily", "lil"],
  ["lucas", "luke", "luca"],
  ["madeline", "maddie", "madge", "madeleine"],
  ["margaret", "maggie", "meg", "peggy", "marge", "margo", "greta", "rita"],
  ["maria", "marie", "mary", "mia"],
  ["marjorie", "margie", "marge"],
  ["martha", "marty", "mattie"],
  ["martin", "marty"],
  ["mary", "molly", "polly", "mamie", "mae"],
  ["matthew", "matt", "matty"],
  ["maximilian", "max", "maxim"],
  ["megan", "meg", "meghan"],
  ["melissa", "mel", "lissa", "missy"],
  ["michael", "mike", "mikey", "mick", "mickey", "misha"],
  ["michelle", "shelly", "mich"],
  ["mikhail", "misha", "michael"],
  ["nancy", "nan"],
  ["natalie", "nat", "natasha", "natalia"],
  ["nathan", "nate", "nat"],
  ["nathaniel", "nate", "nat", "nathan"],
  ["nicholas", "nick", "nico", "cole", "nicky"],
  ["nicole", "nikki", "nicky", "cole"],
  ["oliver", "ollie"],
  ["olivia", "liv", "livvy", "ollie"],
  ["pamela", "pam"],
  ["patricia", "pat", "patty", "tricia", "trish"],
  ["patrick", "pat", "paddy", "rick"],
  ["penelope", "penny"],
  ["peter", "pete", "petey"],
  ["philip", "phil", "phillip", "pip"],
  ["priscilla", "cilla", "priss"],
  ["rachel", "rae"],
  ["raymond", "ray"],
  ["rebecca", "becky", "becca", "beck"],
  ["richard", "rick", "ricky", "dick", "rich", "richie"],
  ["robert", "rob", "bob", "bobby", "robbie", "bert"],
  ["roberta", "bobbie", "berta"],
  ["roderick", "rod", "roddy"],
  ["ronald", "ron", "ronnie"],
  ["rosemary", "rose", "rosie", "romy"],
  ["russell", "russ", "rusty"],
  ["samantha", "sam", "sammy"],
  ["samuel", "sam", "sammy"],
  ["sandra", "sandy"],
  ["sarah", "sara", "sally", "sadie"],
  ["scott", "scotty"],
  ["sebastian", "seb", "bastian"],
  ["sergei", "sergey", "serge"],
  ["sidney", "sid", "sydney", "syd"],
  ["sophia", "sophie", "sofia", "sofie"],
  ["stephanie", "steph", "stephie"],
  ["stephen", "steve", "steven", "stevie"],
  ["stuart", "stu", "stewart"],
  ["susan", "sue", "susie", "suzanne", "suzy"],
  ["teresa", "terry", "tess", "theresa", "tessa"],
  ["theodore", "ted", "teddy", "theo"],
  ["thomas", "tom", "tommy", "thom"],
  ["timothy", "tim", "timmy"],
  ["tobias", "toby"],
  ["valentina", "val", "tina"],
  ["valerie", "val"],
  ["vanessa", "nessa", "van"],
  ["veronica", "ronnie", "vera", "nica"],
  ["victoria", "vicky", "tori", "vic"],
  ["vincent", "vince", "vinny"],
  ["virginia", "ginny", "ginger"],
  ["walter", "walt", "wally"],
  ["wendy", "wen"],
  ["william", "will", "bill", "billy", "willy", "liam"],
  ["winifred", "winnie", "freda"],
  ["zachary", "zach", "zack", "zak"],
];

// name → set of group indices (a nickname like "al" belongs to several).
const INDEX = new Map<string, number[]>();
GROUPS.forEach((group, gi) => {
  for (const name of group) {
    const list = INDEX.get(name) ?? [];
    list.push(gi);
    INDEX.set(name, list);
  }
});

/** True when two first-name tokens are nickname-equivalent (or equal). */
export function nicknamesMatch(a: string, b: string): boolean {
  const na = a.trim().toLowerCase();
  const nb = b.trim().toLowerCase();
  if (!na || !nb) return false;
  if (na === nb) return true;
  const ga = INDEX.get(na);
  const gb = INDEX.get(nb);
  if (!ga || !gb) return false;
  return ga.some((g) => gb.includes(g));
}

/** All known equivalents for a name token (itself included), for search. */
export function nicknameEquivalents(name: string): string[] {
  const n = name.trim().toLowerCase();
  const groups = INDEX.get(n);
  if (!groups) return [n];
  const out = new Set<string>([n]);
  for (const gi of groups) for (const member of GROUPS[gi]) out.add(member);
  return [...out];
}
